# Generated by Django 6.0 on 2026-01-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('fiscal', '0001_cfdi_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='fiscal.cfdicertificate', verbose_name='Certificado activo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización SAT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre oficial para el SAT', max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida')], default='active', max_length=20, verbose_name='Estado'),
        ),
    ]
