# Generated by Django 6.0 on 2026-01-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_cfdi_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='empresa',
            name='last_mass_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última descarga masiva SAT'),
        ),
    ]
