# Generated by Django 6.0 on 2026-01-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_last_sync'),
        ('fiscal', '0003_add_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='fiscal.regimenfiscal', verbose_name='Régimen Fiscal'),
        ),
    ]
