# Generated by Django 6.0 on 2026-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal del domicilio fiscal (requerido para CFDI 4.0)', max_length=5, null=True, verbose_name='Código Postal'),
        ),
    ]
