# Generated by Django 6.0 on 2026-01-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_url', models.URLField(help_text='Ej: http://localhost:8069 o https://mi-empresa.odoo.com', verbose_name='URL de Odoo')),
                ('odoo_db', models.CharField(max_length=100, verbose_name='Base de datos Odoo')),
                ('odoo_username', models.CharField(max_length=150, verbose_name='Usuario Odoo')),
                ('encrypted_password', models.TextField(help_text='Almacenada de forma segura usando Fernet', verbose_name='Contraseña encriptada')),
                ('odoo_company_id', models.IntegerField(help_text='res.company ID en Odoo', verbose_name='ID Empresa en Odoo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('error', 'Error de conexión')], default='active', max_length=20, verbose_name='Estado')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último error')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Sincronizar automáticamente al descargar CFDIs del SAT', verbose_name='Sincronización automática')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_connection', to='companies.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Conexión Odoo',
                'verbose_name_plural': 'Conexiones Odoo',
            },
        ),
        migrations.CreateModel(
            name='OdooSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfdi_uuid', models.UUIDField(verbose_name='UUID del CFDI')),
                ('direction', models.CharField(choices=[('to_odoo', 'Hacia Odoo'), ('from_odoo', 'Desde Odoo')], default='to_odoo', max_length=20, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('success', 'Exitoso'), ('error', 'Error'), ('skipped', 'Omitido')], default='pending', max_length=20, verbose_name='Estado')),
                ('odoo_invoice_id', models.IntegerField(blank=True, help_text='account.move ID si fue creada/encontrada', null=True, verbose_name='ID Factura en Odoo')),
                ('action_taken', models.CharField(blank=True, help_text='created, updated, verified, skipped', max_length=50, null=True, verbose_name='Acción realizada')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Payload enviado')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Respuesta de Odoo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.odooconnection', verbose_name='Conexión')),
            ],
            options={
                'verbose_name': 'Log de Sincronización Odoo',
                'verbose_name_plural': 'Logs de Sincronización Odoo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cfdi_uuid'], name='integration_cfdi_uu_736e2e_idx'), models.Index(fields=['connection', '-created_at'], name='integration_connect_ce81b6_idx'), models.Index(fields=['status'], name='integration_status_ead0b1_idx')],
            },
        ),
    ]
