# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, help_text='Modelo Django afectado (ej: CfdiDocument, Poliza)', max_length=100, verbose_name='Tipo de entidad')),
                ('entity_id', models.CharField(db_index=True, help_text='PK del registro afectado', max_length=255, verbose_name='ID de entidad')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('status_change', 'Cambio de Estado'), ('import', 'Importación'), ('export', 'Exportación'), ('download', 'Descarga'), ('upload', 'Carga'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('permission_change', 'Cambio de Permisos')], db_index=True, max_length=50, verbose_name='Acción')),
                ('payload_before', models.JSONField(blank=True, help_text='Snapshot del estado antes del cambio', null=True, verbose_name='Estado anterior')),
                ('payload_after', models.JSONField(blank=True, help_text='Snapshot del estado después del cambio', null=True, verbose_name='Estado posterior')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de origen de la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador/cliente utilizado', null=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, help_text='Contexto adicional de la acción', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('empresa', models.ForeignKey(help_text='Contexto de tenant para el evento', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción (null = sistema automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', '-created_at'], name='core_auditl_empresa_26a5e2_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='core_auditl_entity__1c230b_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
