# Generated by Django 6.0 on 2026-01-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='empresa',
            field=models.ForeignKey(help_text='Contexto de tenant obligatorio para multi-tenant estricto', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.empresa', verbose_name='Empresa'),
        ),
    ]
