# Generated by Django 6.0 on 2026-01-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13, verbose_name='RFC')),
                ('cert_path_encrypted', models.CharField(max_length=500, verbose_name='Path cifrado del certificado (.cer)')),
                ('key_path_encrypted', models.CharField(max_length=500, verbose_name='Path cifrado de la llave (.key)')),
                ('key_password_encrypted', models.CharField(max_length=500, verbose_name='Contraseña cifrada de la llave')),
                ('valid_from', models.DateTimeField(verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido hasta')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('revoked', 'Revocado')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Certificado CFDI',
                'verbose_name_plural': 'Certificados CFDI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rfc', 'status'], name='fiscal_cfdi_rfc_eab9c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CfdiDocument',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='UUID')),
                ('rfc_emisor', models.CharField(db_index=True, max_length=13, verbose_name='RFC Emisor')),
                ('rfc_receptor', models.CharField(db_index=True, max_length=13, verbose_name='RFC Receptor')),
                ('tipo_cfdi', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('P', 'Pago'), ('T', 'Traslado')], max_length=1, verbose_name='Tipo de CFDI')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('fecha_emision', models.DateTimeField(db_index=True, verbose_name='Fecha de emisión')),
                ('estado_sat', models.CharField(choices=[('Vigente', 'Vigente'), ('Cancelado', 'Cancelado')], default='Vigente', max_length=20, verbose_name='Estado SAT')),
                ('estado_cancelacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de cancelación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('s3_key', models.CharField(max_length=500, verbose_name='Llave S3 del XML')),
                ('last_state_check', models.DateTimeField(blank=True, null=True, verbose_name='Última verificación de estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdi_documents', to='companies.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Documento CFDI',
                'verbose_name_plural': 'Documentos CFDI',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CfdiDownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id_sat', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de solicitud SAT')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('tipo', models.CharField(choices=[('emitidos', 'Emitidos'), ('recibidos', 'Recibidos')], max_length=20, verbose_name='Tipo de descarga')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('ready', 'Listo'), ('downloaded', 'Descargado'), ('failed', 'Fallido')], default='requested', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdi_download_requests', to='companies.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Solicitud de descarga CFDI',
                'verbose_name_plural': 'Solicitudes de descarga CFDI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CfdiStateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sat', models.CharField(max_length=20, verbose_name='Estado SAT')),
                ('estado_cancelacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado de cancelación')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de verificación')),
                ('source', models.CharField(choices=[('uuid_check', 'Verificación individual'), ('mass_download', 'Descarga masiva')], max_length=20, verbose_name='Fuente')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_checks', to='fiscal.cfdidocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Verificación de estado CFDI',
                'verbose_name_plural': 'Verificaciones de estado CFDI',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['company', 'fecha_emision'], name='fiscal_cfdi_company_477b16_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['company', 'tipo_cfdi'], name='fiscal_cfdi_company_3986fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['company', 'estado_sat'], name='fiscal_cfdi_company_e49599_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidownloadrequest',
            index=models.Index(fields=['company', 'status'], name='fiscal_cfdi_company_630a94_idx'),
        ),
    ]
