# Generated by Django 6.0 on 2026-01-10 07:36

from django.db import migrations, models


def certificate_upload_path(instance, filename):
    """Función legacy para migraciones - ya no se usa en el modelo actual."""
    return f'cfdi/certificates/{instance.rfc}/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_cfdi_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='cert_path_encrypted',
        ),
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='key_path_encrypted',
        ),
        migrations.RemoveField(
            model_name='cfdidocument',
            name='s3_key',
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='cert_file',
            field=models.FileField(blank=True, upload_to=certificate_upload_path, verbose_name='Archivo de certificado (.cer)'),
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='key_file',
            field=models.FileField(blank=True, upload_to=certificate_upload_path, verbose_name='Archivo de llave (.key)'),
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='xml_file',
            field=models.FileField(blank=True, upload_to='cfdi/documents/%Y/%m/', verbose_name='Archivo XML'),
        ),
    ]
