# Generated by Django 6.0 on 2026-01-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_use_filefields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Código del régimen según catálogo SAT', max_length=3, unique=True, verbose_name='Clave SAT')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Tipo de persona')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Régimen Fiscal',
                'verbose_name_plural': 'Regímenes Fiscales',
                'ordering': ['clave'],
            },
        ),
    ]
