# Generated by Django 6.0 on 2026-01-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_add_regimen_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Código de la forma de pago según catálogo SAT', max_length=2, unique=True, verbose_name='Clave SAT')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='UsoCfdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Código del uso según catálogo SAT', max_length=4, unique=True, verbose_name='Clave SAT')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Aplica a')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Uso de CFDI',
                'verbose_name_plural': 'Usos de CFDI',
                'ordering': ['clave'],
            },
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('PUE', 'Pago en Una sola Exhibición'), ('PPD', 'Pago en Parcialidades o Diferido')], help_text='PUE = Una exhibición, PPD = Parcialidades', max_length=3, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='fiscal.formapago', verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='uso_cfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='fiscal.usocfdi', verbose_name='Uso de CFDI'),
        ),
    ]
