# Generated by Django 6.0 on 2026-01-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_add_uso_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatDownloadPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id_sat', models.CharField(max_length=100, verbose_name='ID del paquete SAT')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('downloading', 'Descargando'), ('downloaded', 'Descargado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('file', models.FileField(blank=True, upload_to='cfdi/packages/%Y/%m/', verbose_name='Archivo del paquete')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash SHA256')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('cfdi_count', models.PositiveIntegerField(default=0, verbose_name='CFDIs en el paquete')),
                ('cfdi_processed', models.PositiveIntegerField(default=0, verbose_name='CFDIs procesados')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
            ],
            options={
                'verbose_name': 'Paquete de descarga SAT',
                'verbose_name_plural': 'Paquetes de descarga SAT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='xml_hash',
            field=models.CharField(blank=True, help_text='Para validar integridad post-descarga', max_length=64, null=True, verbose_name='Hash SHA256 del XML'),
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='xml_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del XML (bytes)'),
        ),
        migrations.AddField(
            model_name='cfdistatecheck',
            name='es_cambio',
            field=models.BooleanField(default=False, help_text='True si el estado cambió respecto al anterior', verbose_name='¿Hubo cambio?'),
        ),
        migrations.AddField(
            model_name='cfdistatecheck',
            name='estado_anterior',
            field=models.CharField(blank=True, help_text='Estado antes de esta verificación', max_length=20, null=True, verbose_name='Estado anterior'),
        ),
        migrations.AddField(
            model_name='cfdistatecheck',
            name='response_raw',
            field=models.TextField(blank=True, help_text='Respuesta completa del SAT para debugging', null=True, verbose_name='Respuesta SAT (raw)'),
        ),
        migrations.AlterField(
            model_name='cfdistatecheck',
            name='source',
            field=models.CharField(choices=[('uuid_check', 'Verificación individual'), ('mass_download', 'Descarga masiva'), ('manual', 'Corrección manual'), ('webhook', 'Notificación SAT')], max_length=20, verbose_name='Fuente'),
        ),
        migrations.AddIndex(
            model_name='cfdistatecheck',
            index=models.Index(fields=['document', 'checked_at'], name='fiscal_cfdi_documen_9658c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdistatecheck',
            index=models.Index(fields=['es_cambio', 'checked_at'], name='fiscal_cfdi_es_camb_ec6d8b_idx'),
        ),
        migrations.AddField(
            model_name='satdownloadpackage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='fiscal.cfdidownloadrequest', verbose_name='Solicitud'),
        ),
        migrations.AddIndex(
            model_name='satdownloadpackage',
            index=models.Index(fields=['request', 'status'], name='fiscal_satd_request_fa282c_idx'),
        ),
    ]
