# Generated by Django 6.0 on 2026-01-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        ('fiscal', '0005_production_ready_adjustments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='cert_file',
        ),
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='key_file',
        ),
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='key_password_encrypted',
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='companies.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='key_password_ref',
            field=models.CharField(default='', help_text='ej: secretsmanager:cfdi/company-123/rfc-ABC/csd-password', max_length=255, verbose_name='Referencia a la contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='s3_cer_path',
            field=models.CharField(default='', help_text='ej: cfdi-secrets/123/RFC123/csd/2024-01.cer', max_length=500, verbose_name='Ruta S3 del certificado (.cer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='s3_key_path',
            field=models.CharField(default='', help_text='ej: cfdi-secrets/123/RFC123/csd/2024-01.key', max_length=500, verbose_name='Ruta S3 de la llave (.key)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie'),
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='tipo',
            field=models.CharField(choices=[('CSD', 'Certificado de Sello Digital'), ('FIEL', 'Firma Electrónica Avanzada')], default='CSD', max_length=4, verbose_name='Tipo de certificado'),
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
