# Generated by Django 6.0 on 2026-01-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        ('fiscal', '0006_secure_certificate_storage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cfdidocument',
            name='fiscal_cfdi_company_e49599_idx',
        ),
        migrations.RemoveIndex(
            model_name='cfdistatecheck',
            name='fiscal_cfdi_documen_9658c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='cfdistatecheck',
            name='fiscal_cfdi_es_camb_ec6d8b_idx',
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='s3_xml_path',
            field=models.CharField(blank=True, help_text='ej: cfdi/xml/2024/01/UUID.xml', max_length=500, null=True, verbose_name='Ruta S3 del XML'),
        ),
        migrations.AlterField(
            model_name='cfdidocument',
            name='estado_cancelacion',
            field=models.CharField(blank=True, choices=[('Cancelable sin aceptación', 'Cancelable sin aceptación'), ('Cancelable con aceptación', 'Cancelable con aceptación'), ('No cancelable', 'No cancelable')], max_length=50, null=True, verbose_name='Estado de cancelación'),
        ),
        migrations.AlterField(
            model_name='cfdidocument',
            name='estado_sat',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Cancelado', 'Cancelado'), ('No Encontrado', 'No Encontrado')], default='Vigente', max_length=20, verbose_name='Estado SAT'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['estado_sat'], name='fiscal_cfdi_estado__eca9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['last_state_check'], name='fiscal_cfdi_last_st_316d84_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdistatecheck',
            index=models.Index(fields=['document', '-checked_at'], name='fiscal_cfdi_documen_3dfe4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cfdidocument',
            constraint=models.UniqueConstraint(fields=('company', 'uuid'), name='unique_cfdi_per_company'),
        ),
        migrations.RemoveField(
            model_name='cfdidocument',
            name='xml_file',
        ),
    ]
