# Generated by Django 6.0 on 2026-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_production_ready_cfdi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satdownloadpackage',
            name='file',
        ),
        migrations.AddField(
            model_name='satdownloadpackage',
            name='s3_zip_path',
            field=models.CharField(blank=True, help_text='ej: cfdi/packages/2024/01/package_123.zip', max_length=500, null=True, verbose_name='Ruta S3 del ZIP'),
        ),
    ]
