# Generated by Django 6.0 on 2026-01-10 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        ('fiscal', '0008_production_ready_sat_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiParserVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfdi_version', models.CharField(db_index=True, help_text='ej: 3.3, 4.0', max_length=10, verbose_name='Versión CFDI')),
                ('xsd_version', models.CharField(help_text='Versión del esquema XSD publicado por SAT', max_length=50, verbose_name='Versión XSD')),
                ('xsd_hash', models.CharField(help_text='Para validar que no fue modificado', max_length=64, verbose_name='Hash SHA256 del XSD')),
                ('sat_release_date', models.DateField(help_text='Fecha en que el SAT publicó esta versión', verbose_name='Fecha de publicación SAT')),
                ('valid_from', models.DateField(help_text='Fecha desde la cual se debe usar esta versión', verbose_name='Válido desde')),
                ('valid_to', models.DateField(blank=True, help_text='Fecha hasta la cual esta versión es válida (null = actual)', null=True, verbose_name='Válido hasta')),
                ('notes', models.TextField(blank=True, help_text='Cambios significativos en esta versión', null=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Versión Parser CFDI',
                'verbose_name_plural': 'Versiones Parser CFDI',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='current_state_check',
            field=models.ForeignKey(blank=True, help_text='FUENTE DE VERDAD - Última verificación oficial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fiscal.cfdistatecheck', verbose_name='Verificación de estado actual'),
        ),
        migrations.AddField(
            model_name='cfdidownloadrequest',
            name='request_payload_hash',
            field=models.CharField(blank=True, help_text='Hash del request enviado al SAT (para detectar duplicados)', max_length=64, null=True, verbose_name='Hash SHA256 del payload'),
        ),
        migrations.AddField(
            model_name='cfdidownloadrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que inició la descarga (null = automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdi_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='cfdidownloadrequest',
            name='sat_response_raw',
            field=models.TextField(blank=True, help_text='Respuesta XML/JSON completa del SAT (debugging)', null=True, verbose_name='Respuesta SAT completa'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='sat_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión catálogo SAT'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Válido desde'),
        ),
        migrations.AddField(
            model_name='formapago',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Válido hasta'),
        ),
        migrations.AddField(
            model_name='regimenfiscal',
            name='sat_version',
            field=models.CharField(blank=True, help_text='Versión del catálogo del SAT (ej: 2024-01, 2025-06)', max_length=50, null=True, verbose_name='Versión catálogo SAT'),
        ),
        migrations.AddField(
            model_name='regimenfiscal',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Fecha desde la cual este régimen es válido según SAT', null=True, verbose_name='Válido desde'),
        ),
        migrations.AddField(
            model_name='regimenfiscal',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual este régimen es válido (null = vigente)', null=True, verbose_name='Válido hasta'),
        ),
        migrations.AddField(
            model_name='usocfdi',
            name='sat_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión catálogo SAT'),
        ),
        migrations.AddField(
            model_name='usocfdi',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Válido desde'),
        ),
        migrations.AddField(
            model_name='usocfdi',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Válido hasta'),
        ),
        migrations.AlterField(
            model_name='cfdidocument',
            name='estado_cancelacion',
            field=models.CharField(blank=True, choices=[('Cancelable sin aceptación', 'Cancelable sin aceptación'), ('Cancelable con aceptación', 'Cancelable con aceptación'), ('No cancelable', 'No cancelable')], help_text='CACHE - La fuente de verdad es current_state_check', max_length=50, null=True, verbose_name='Estado de cancelación (cache)'),
        ),
        migrations.AlterField(
            model_name='cfdidocument',
            name='estado_sat',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Cancelado', 'Cancelado'), ('No Encontrado', 'No Encontrado')], default='Vigente', help_text='CACHE - La fuente de verdad es current_state_check', max_length=20, verbose_name='Estado SAT (cache)'),
        ),
        migrations.AddIndex(
            model_name='cfdidownloadrequest',
            index=models.Index(fields=['company', '-created_at'], name='fiscal_cfdi_company_6b1fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidownloadrequest',
            index=models.Index(fields=['requested_by', '-created_at'], name='fiscal_cfdi_request_bcc024_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdistatecheck',
            index=models.Index(fields=['es_cambio', '-checked_at'], name='fiscal_cfdi_es_camb_dd716b_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdistatecheck',
            index=models.Index(fields=['source', '-checked_at'], name='fiscal_cfdi_source_a2bbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='satdownloadpackage',
            index=models.Index(fields=['status', '-created_at'], name='fiscal_satd_status_fb1127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cfdiparserversion',
            unique_together={('cfdi_version', 'xsd_version')},
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='parser_version',
            field=models.ForeignKey(blank=True, help_text='Versión XSD con la que se procesó este CFDI', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fiscal.cfdiparserversion', verbose_name='Versión de parser'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['company', 'rfc_emisor', 'fecha_emision'], name='fiscal_cfdi_company_f3178f_idx'),
        ),
        migrations.AddIndex(
            model_name='cfdidocument',
            index=models.Index(fields=['company', 'rfc_receptor', 'fecha_emision'], name='fiscal_cfdi_company_3c3737_idx'),
        ),
    ]
