# Generated by Django 6.0 on 2026-01-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_cfdiparserversion_cfdidocument_current_state_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdidocument',
            name='download_package',
            field=models.ForeignKey(blank=True, help_text='Paquete SAT del cual proviene (si source=SAT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='fiscal.satdownloadpackage', verbose_name='Paquete de descarga SAT'),
        ),
        migrations.AddField(
            model_name='cfdidocument',
            name='source',
            field=models.CharField(choices=[('SAT', 'Descarga SAT'), ('Proveedor', 'Recibido de Proveedor'), ('CargaManual', 'Carga Manual')], default='SAT', help_text='Fuente desde la cual se obtuvo este CFDI', max_length=20, verbose_name='Origen del CFDI'),
        ),
        migrations.AddField(
            model_name='cfdistatecheck',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='CSD/FIEL con el que se realizó la consulta al SAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_checks', to='fiscal.cfdicertificate', verbose_name='Certificado usado'),
        ),
    ]
