# Generated by Django 6.0 on 2026-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_cfdidocument_download_package_cfdidocument_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdicertificate',
            name='key_password_ref',
        ),
        migrations.AddField(
            model_name='cfdicertificate',
            name='encrypted_password',
            field=models.TextField(default='gAAAAABplaceholderEncryptedValue==', help_text='Almacenada de forma segura usando Fernet', verbose_name='Contraseña encriptada'),
            preserve_default=False,
        ),
    ]
