# Generated by Django 6.0 on 2026-01-11 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_add_uso_forma_pago'),
        ('fiscal', '0011_remove_cfdicertificate_key_password_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdidownloadrequest',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True si fue generado por el worker de sincronización automática', verbose_name='Generación automática'),
        ),
        migrations.CreateModel(
            name='EmpresaSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Si está activo, el sistema descargará facturas nuevas diariamente', verbose_name='Sincronización automática activada')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización exitosa')),
                ('sync_frequency_hours', models.IntegerField(default=24, help_text='Cada cuánto tiempo sincronizar', verbose_name='Frecuencia (horas)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_settings', to='companies.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Sincronización',
                'verbose_name_plural': 'Configuraciones de Sincronización',
            },
        ),
    ]
