# Generated by Django 6.0 on 2026-01-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0012_cfdidownloadrequest_is_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasyncsettings',
            name='scheduled_start_hour',
            field=models.IntegerField(blank=True, help_text='Si se define, la sincronización ocurrirá diariamente a esta hora aprox.', null=True, verbose_name='Hora de inicio programada (0-23)'),
        ),
        migrations.AlterField(
            model_name='empresasyncsettings',
            name='sync_frequency_hours',
            field=models.IntegerField(default=24, help_text='Cada cuánto tiempo sincronizar. Ignorado si se define hora de inicio.', verbose_name='Frecuencia (horas)'),
        ),
    ]
