# Generated by Django 6.0 on 2026-01-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0013_empresasyncsettings_scheduled_start_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasyncsettings',
            name='scheduled_start_hour',
            field=models.IntegerField(default=3, help_text='Hora del día para ejecutar la sincronización diaria (0-23). Por defecto 3 AM.', verbose_name='Hora de inicio diaria (0-23)'),
        ),
        migrations.AlterField(
            model_name='empresasyncsettings',
            name='sync_frequency_hours',
            field=models.IntegerField(default=24, help_text='DEPRECADO (Fijo a 24h). El sistema ahora sincroniza diariamente en la hora programada.', verbose_name='Frecuencia (horas)'),
        ),
    ]
