# Generated by Django 6.0 on 2026-01-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0014_alter_empresasyncsettings_scheduled_start_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasyncsettings',
            name='last_weekly_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización semanal exitosa'),
        ),
        migrations.AddField(
            model_name='empresasyncsettings',
            name='sync_to_odoo_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, los CFDIs descargados se sincronizarán automáticamente a Odoo', verbose_name='Sincronizar a Odoo'),
        ),
        migrations.AddField(
            model_name='empresasyncsettings',
            name='weekly_sync_day',
            field=models.IntegerField(default=0, help_text='Día de la semana para ejecutar la sincronización semanal', verbose_name='Día de ejecución semanal (0=Lunes, 6=Domingo)'),
        ),
        migrations.AddField(
            model_name='empresasyncsettings',
            name='weekly_sync_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, el sistema descargará facturas de la semana anterior y sincronizará a Odoo', verbose_name='Sincronización semanal activada'),
        ),
        migrations.AddField(
            model_name='empresasyncsettings',
            name='weekly_sync_hour',
            field=models.IntegerField(default=4, help_text='Hora del día para ejecutar la sincronización semanal', verbose_name='Hora de ejecución semanal (0-23)'),
        ),
    ]
