# Generated by Django 6.0 on 2026-01-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0015_empresasyncsettings_weekly_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasyncsettings',
            name='weekly_sync_minute',
            field=models.IntegerField(default=0, help_text='Minuto exacto para ejecutar la sincronización semanal', verbose_name='Minuto de ejecución semanal (0-59)'),
        ),
    ]
