# Generated by Django 6.0 on 2026-01-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0016_add_weekly_sync_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasyncsettings',
            name='weekly_sync_days_range',
            field=models.IntegerField(choices=[(7, 'Última semana (7 días)'), (14, 'Últimas 2 semanas (14 días)'), (21, 'Últimas 3 semanas (21 días)'), (29, 'Último mes (29 días)')], default=7, help_text='Cuántos días hacia atrás descargar en cada sincronización', verbose_name='Rango de días a descargar'),
        ),
    ]
