# Generated by Django 6.0 on 2026-01-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0018_cfdi_add_fields_change_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasyncsettings',
            name='weekly_sync_days_range',
            field=models.IntegerField(
                choices=[
                    (7, 'Última semana (7 días)'),
                    (14, 'Últimas 2 semanas (14 días)'),
                    (21, 'Últimas 3 semanas (21 días)'),
                    (30, 'Último mes (30 días)'),
                    (60, 'Últimos 2 meses (60 días)'),
                    (90, 'Últimos 3 meses (90 días)'),
                    (120, 'Últimos 4 meses (120 días)'),
                    (150, 'Últimos 5 meses (150 días)'),
                    (180, 'Últimos 6 meses (180 días)'),
                    (270, 'Últimos 9 meses (270 días)'),
                    (365, 'Último año (365 días)'),
                ],
                default=7,
                help_text='Cuántos días hacia atrás descargar en cada sincronización',
                verbose_name='Rango de días a descargar'
            ),
        ),
    ]
